import {
  CatalogueIndexSchema,
  CatalogueSchema,
  verifyCatalogue,
  type Catalogue,
  type CatalogueIndex,
} from '@refrain/catalogue';

/**
 * Loading the library.
 *
 * Three things happen before a single record is used: the JSON is parsed
 * against the schema, the catalogue's hash is recomputed and compared, and the
 * result is treated as the only source of truth for what may be shown or
 * played. A file that fails any of those is refused outright rather than
 * partly trusted — that is SEC-2 and SEC-10 at the point of use.
 */

export class CatalogueLoadError extends Error {}

export interface Library {
  index: CatalogueIndex;
  catalogues: Catalogue[];
}

export function assetUrl(relativePath: string): string {
  const base = import.meta.env.BASE_URL || '/';
  return `${base}${relativePath}`;
}

/**
 * The share page for a listening state.
 *
 * Generated by `refrain publish`; kept in step with the pipeline by the shape
 * of the path, which is asserted in both test suites.
 */
export function sharePathFor(corpusId: string, chunkId: string, presetId: string): string {
  return `library/${corpusId}/share/${chunkId}--${presetId}.html`;
}

let probe: HTMLAudioElement | null = null;

/**
 * What this browser says it can decode.
 *
 * One detached `<audio>` element answers for the whole app, and the answer is
 * asked of the browser rather than inferred from the user agent — which is the
 * only way to get Safari's AAC and everyone else's Opus right without a list
 * of user-agent strings to maintain.
 */
export function canPlayType(mimeType: string): 'probably' | 'maybe' | '' {
  if (typeof document === 'undefined') return '';
  probe ??= document.createElement('audio');
  return probe.canPlayType(mimeType) as 'probably' | 'maybe' | '';
}

async function fetchJson(url: string): Promise<unknown> {
  const response = await fetch(url, { credentials: 'omit' });
  if (!response.ok) {
    throw new CatalogueLoadError(`${url} returned ${response.status}`);
  }
  return (await response.json()) as unknown;
}

export async function loadLibrary(): Promise<Library> {
  const raw = await fetchJson(assetUrl('library/index.json'));
  const parsedIndex = CatalogueIndexSchema.safeParse(raw);
  if (!parsedIndex.success) {
    throw new CatalogueLoadError(
      `the library index does not match the schema: ${parsedIndex.error.issues[0]?.message ?? 'unknown'}`,
    );
  }
  const index = parsedIndex.data;

  const catalogues: Catalogue[] = [];
  for (const entry of index.corpora) {
    const catalogue = await loadCatalogue(entry.path);
    if (catalogue.corpus.id !== entry.id) {
      throw new CatalogueLoadError(
        `the index lists ${entry.id} but ${entry.path} contains ${catalogue.corpus.id}`,
      );
    }
    catalogues.push(catalogue);
  }
  if (catalogues.length === 0) throw new CatalogueLoadError('the library index is empty');
  return { index, catalogues };
}

export async function loadCatalogue(relativePath: string): Promise<Catalogue> {
  const parsed = CatalogueSchema.safeParse(await fetchJson(assetUrl(relativePath)));
  if (!parsed.success) {
    throw new CatalogueLoadError(
      `${relativePath} does not match the catalogue schema: ${parsed.error.issues[0]?.message ?? 'unknown'}`,
    );
  }
  const catalogue = parsed.data;
  if (!(await verifyCatalogue(catalogue))) {
    throw new CatalogueLoadError(
      `${relativePath} failed its integrity check: the file does not match its own content hash`,
    );
  }
  return catalogue;
}

/** The chunks of one book, in reading order. */
export function chunksInBook(catalogue: Catalogue, bookId: string) {
  return catalogue.chunks.filter((c) => c.bookId === bookId).sort((a, b) => a.number - b.number);
}

/** Which styles and voices actually have a published track for this chunk. */
export function availableFor(catalogue: Catalogue, chunkId: string) {
  const presetIds = new Set(
    catalogue.tracks.filter((t) => t.chunkId === chunkId).map((t) => t.presetId),
  );
  const presets = catalogue.presets.filter((p) => presetIds.has(p.id));
  return {
    presets,
    styles: catalogue.styles.filter((s) => presets.some((p) => p.styleId === s.id)),
    voices: catalogue.voices.filter((v) => presets.some((p) => p.voiceId === v.id)),
  };
}

export function findTrack(catalogue: Catalogue, chunkId: string, presetId: string) {
  return catalogue.tracks.find((t) => t.chunkId === chunkId && t.presetId === presetId) ?? null;
}
